# Changes here will be overwritten by Copier
_commit: v2.0.7
_src_path: gh:lincc-frameworks/python-project-template
author_email: steven.stetzler@gmail.com
author_name: Steven Stetzler
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
- pylint
- black
- isort
failure_notification:
- email
- slack
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: basic
package_name: salad
project_license: MIT
project_name: salad
project_organization: dirac-institute
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: direct
